//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace WindowsPhone.Profiler
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vs/profiler/ProfilingTasks/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("ProfilingTasks", Namespace = "http://schemas.microsoft.com/vs/profiler/ProfilingTasks/1.0", IsNullable = false)]
    public partial class ProfilingTasksType
    {
        [XmlAttribute(AttributeName = "noNamespaceSchemaLocation", Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
        public string Schema = @"file:ProfilingTasks.xsd";

        private TaskType[] taskField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TaskType[] Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vs/profiler/ProfilingTasks/1.0")]
    public partial class TaskType
    {

        private EtwProviderType[] etwProviderField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EtwProvider", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EtwProviderType[] EtwProvider
        {
            get
            {
                return this.etwProviderField;
            }
            set
            {
                this.etwProviderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vs/profiler/ProfilingTasks/1.0")]
    public partial class EtwProviderType
    {

        private string nameField;

        private string gUIDField;

        private XmlProviderLevel levelField;

        private string hexKeywordsField;

        private bool kernelModeField;

        private string kernelStackHexKeywordsField;

        private bool cLRField;

        public EtwProviderType()
        {
            this.gUIDField = "{00000000-0000-0000-0000-000000000000}";
            this.levelField = XmlProviderLevel.Verbose;
            this.hexKeywordsField = "00000000";
            this.kernelModeField = false;
            this.kernelStackHexKeywordsField = "00000000";
            this.cLRField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("{00000000-0000-0000-0000-000000000000}")]
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(XmlProviderLevel.Verbose)]
        public XmlProviderLevel Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("00000000")]
        public string HexKeywords
        {
            get
            {
                return this.hexKeywordsField;
            }
            set
            {
                this.hexKeywordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool KernelMode
        {
            get
            {
                return this.kernelModeField;
            }
            set
            {
                this.kernelModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("00000000")]
        public string KernelStackHexKeywords
        {
            get
            {
                return this.kernelStackHexKeywordsField;
            }
            set
            {
                this.kernelStackHexKeywordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CLR
        {
            get
            {
                return this.cLRField;
            }
            set
            {
                this.cLRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vs/profiler/ProfilingTasks/1.0")]
    public enum XmlProviderLevel
    {

        /// <remarks/>
        Always,

        /// <remarks/>
        Critical,

        /// <remarks/>
        Error,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Informational,

        /// <remarks/>
        Verbose,
    }
}